name: My First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: echo "checking code"

      - name: Print message
        run: echo "Pipeline is working 🚀"

      - name: Run script
        run: echo "RUNNED SCRIPT"
